# Syngestures configuration file, version 1

# This file should be placed in any of the following paths.
# * $PREFIX/syngestures.toml (for global configuration)
# * $PREFIX/syngestures.d/*.toml (for global configuration, separate file per device)
# * $XDG_CONFIG_HOME/syngestures.toml (for per-user configuration)
# * $XDG_CONFIG_HOME/syngestures.d/*.toml (for per-user configuration, separate file per device)
#
# If $XDG_CONFIG_HOME is not set, $HOME/.config/ is used in its place.

[[device]]
device = "/dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse"
gestures = [
	# Emulate right-click. Don't use this if two-finger tap to right-click already works
	# { type = "tap", fingers = 2, execute = "xdotool click 3" },

	# Emulate middle-click.
	# The first *should* work but often doesn't; the second *does* but mainly in web browsers.
	# { type = "tap", fingers = 3, execute = "xdotool click 2" },
	# { type = "tap", fingers = 3, execute = "xdotool keydown Control click 1 keyup Control" },

	# Navigate next
	{ type = "swipe", direction = "right", fingers = 3, execute = "xdotool key alt+Right" },
	# Navigate previous
	{ type = "swipe", direction = "left", fingers = 3, execute = "xdotool key alt+Left" },
	# Next desktop/workspace
	{ type = "swipe", direction = "right", fingers = 4, execute = "xdotool key Super_L+Right" },
	# Previous desktop/workspace
	{ type = "swipe", direction = "left", fingers = 4, execute = "xdotool key Super_L+Left" },

	# Enter multi-tasking view
	{ type = "swipe", direction = "up", fingers = 4, execute = "xdotool key Super_L+Down" },
	# Leave multi-tasking view
	{ type = "swipe", direction = "down", fingers = 4, execute = "xdotool key Super_L+Down" },
]
